service: local-news-backend

provider:
  name: aws
  runtime: python3.8
  stage: dev

package:
  individually: true

functions:
  getNewArticles:
    handler: functions/getNewArticles/handler.main

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
