service: local-news-backend

provider:
  name: aws
  runtime: python3.7
  profile: ryan
  stage: dev
  region: us-east-1

package:
  exclude:
    - venv/** # virtualenv

functions:
  getNewArticles:
    handler: functions/getNewArticles/handler.main

plugins:
  - serverless-python-requirements

# custom:
#   pythonRequirements:
#     dockerizePip: non-linux
